plugins {
  // https://github.com/nemerosa/versioning
  id 'net.nemerosa.versioning' version '3.1.0'
}

ext {
  testingCommonGradle = "../testing_common/common.gradle"
  interlokTestingVersion = "0.1"
  restAssuredVersion = "5.5.0"

  includeWar='true'
}

allprojects {
  apply from: "${testingCommonGradle}"
  // specify the version of the configuration.
  version=versioning.info.full
}


dependencies {
  interlokRuntime ("com.adaptris:interlok-webspheremq:$interlokVersion") { changing=true }
  testImplementation group: "com.adaptris", name: "interlok-testing-common", version: "$interlokTestingVersion"
  testImplementation "io.rest-assured:rest-assured:$restAssuredVersion"
  testImplementation "io.rest-assured:json-path:$restAssuredVersion"
  testImplementation "com.ibm.mq:com.ibm.mq.allclient:9.3.0.0"
  interlokJavadocs group: "com.adaptris", name: "interlok-webspheremq", version: "$interlokVersion", classifier: "javadoc", changing: true, transitive: false
}
