version: '2'

services:
  interlok:
    hostname: interlok-1
    build:
      context: .
      dockerfile: dockerfile
  webspheremq:
    image: 'docker.io/ibmcom/mq:latest'
    hostname: 'webspheremq-1'
    environment:
      - MQ_ADMIN_PASSWORD=admin
      - MQ_APP_PASSWORD=admin
      - MQ_QMGR_NAME=DevQueueManager
      - MQ_DEV=true
      - LICENSE=accept
    shm_size: 1g
